import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <title>Ramazan Mermer Sanayi</title>
        <link rel="icon" href="/logo.png" sizes="any" />
        <link
          rel="apple-touch-icon"
          href="/logo.png"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className={`bg-[url('../assets/img/background.jpg')] bg-contain`} style={{ fontFamily: "Arial, sans-serif" }}>
      <ToastContainer theme='dark' />
        {children}
      </body>
    </html>
  )
}
