import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from 'next/font/google'
import BootstrapClient from '@/components/BootstrapClient.js';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      </head>
      <body className={inter.className}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  )
}